title: Dayeon Jung
author: Dayeon Jung
email: fdayeonjung5294@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hi, I’m Dayeon Jung — a Statistician and Data Scientist.  
  I’m passionate about developing statistical methods for high-dimensional data and real-world applications.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Dayeon Jung
  tagline: Statistician & Data Scientist
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.jpeg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  navigation:
    - title: Home
      url: "/"
  social_links:
    #github:  dayeonjung5294
    email: dayeonjung5294@gmail.com
    #linkedIn: in/samarsault
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
# Configure the plugin here
category_path: "category" # <- default value
category_layout: "category.html" # <- default value

# Build settings
# theme: plainwhite

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
